Reinit VERSION

diff --git a/Tools/Git/Hooks/pre-commit b/Tools/Git/Hooks/pre-commit
--- a/Tools/Git/Hooks/pre-commit
+++ b/Tools/Git/Hooks/pre-commit
@@ -1,52 +1,31 @@
 #!/bin/sh
 
 echo "Running pre-commit hook..."
+echo "$(pwd)"
 
-# #
-# # An example hook script to verify what is about to be committed.
-# # Called by "git commit" with no arguments.  The hook should
-# # exit with non-zero status after issuing an appropriate message if
-# # it wants to stop the commit.
-# #
-# # To enable this hook, rename this file to "pre-commit".
-
-# if git rev-parse --verify HEAD >/dev/null 2>&1
-# then
-# 	against=HEAD
+# # Load environment variables
+# if [ -f ../../../../.env ]; then
+#     export $(grep -v '^#' ../../../../.env | xargs)
 # else
-# 	# Initial commit: diff against an empty tree object
-# 	against=$(git hash-object -t tree /dev/null)
+#     echo ".env file not found. Exiting."
+#     exit 1
 # fi
 
-# # If you want to allow non-ASCII filenames set this variable to true.
-# allownonascii=$(git config --type=bool hooks.allownonascii)
+# VERSION_FILE="$ROOT_DIR/VERSION"
 
-# # Redirect output to stderr.
-# exec 1>&2
-
-# # Cross platform projects tend to avoid non-ASCII filenames; prevent
-# # them from being added to the repository. We exploit the fact that the
-# # printable range starts at the space character and ends with tilde.
-# if [ "$allownonascii" != "true" ] &&
-# 	# Note that the use of brackets around a tr range is ok here, (it's
-# 	# even required, for portability to Solaris 10's /usr/bin/tr), since
-# 	# the square bracket bytes happen to fall in the designated range.
-# 	test $(git diff --cached --name-only --diff-filter=A -z $against |
-# 	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
-# then
-# 	cat <<\EOF
-# Error: Attempt to add a non-ASCII file name.
-
-# This can cause problems if you want to work with people on other platforms.
-
-# To be portable it is advisable to rename the file.
-
-# If you know what you are doing you can disable this check using:
-
-#   git config hooks.allownonascii true
-# EOF
-# 	exit 1
+# if [ -f "$VERSION_FILE" ]; then
+#     # Read the current version
+#     VERSION=$(cat "$VERSION_FILE")
+    
+#     # Increment the last number (build/tweak)
+#     IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"
+#     LAST_INDEX=$((${#VERSION_PARTS[@]} - 1))
+#     VERSION_PARTS[$LAST_INDEX]=$((VERSION_PARTS[$LAST_INDEX] + 1))
+#     NEW_VERSION=$(IFS='.'; echo "${VERSION_PARTS[*]}")
+    
+#     # Write the new version back to the file
+#     echo "$NEW_VERSION" > "$VERSION_FILE"
+#     echo "Updated version to $NEW_VERSION"
+# else
+#     echo "VERSION file not found. Skipping version update."
 # fi
-
-# # If there are whitespace errors, print the offending file names and fail.
-# exec git diff-index --check --cached $against --
